import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/Organisms/Header/Header'
import Banner from '@/components/Atoms/Banner'
import ServiceCard from '@/components/Molecules/ServiceCard'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <ServiceCard />
     
    </>
  )
}
